### ISSUE TITLE
Multiple repetitions of same condition in test_5_3

### ISSUE THREAD

**Issue by Koczek9** [rdkcentral/dobby-security-tool#7]
In file `tests/5_dobby_container_runtime_test.sh` there is test `test_5_3` In which there is same line copy-pasted 4 times:
```
if [ "${input[$j]}" == "${ouputarr[$i]}" ]; then
	fail "$check"
	return
elif [ "${input[$j]}" == "${ouputarr[$i]}" ]; then
	fail "$check"
	return
elif [ "${input[$j]}" == "${ouputarr[$i]}" ]; then
	fail "$check"
	return
elif [ "${input[$j]}" == "${ouputarr[$i]}" ]; then
	fail "$check"
	return
fi
```
All those copies doesn't make sense. We could probably delete them, but as there was some if/else I think that author had something in mind just forgot to implement it.

**Comment by Ashoks-hub** [comment]
This issue should fixed by this pull request #19
